### ISSUE TITLE
Adding errors directly to fields

### ISSUE THREAD

**Issue by nyanpasu** [chainlist/svelte-forms#32]
Could we add support for adding errors directly into the fields somehow?

A typical use case would be to handle errors from an API after it has been called.

**Comment by nyanpasu** [comment]
Neat, realized that the `set` and `update` are also exported. Maybe a helper / util method would be nice to have, so that users can add errors without needing to handle the shape of the store.

But otherwise I can still handle this issue on my end. Cheers.

**Comment by chainlist** [comment]
Hi,

A v2 of svelte-forms has been released that fixes this use case.
Check out the new [documentation website](https://chainlist.github.io/svelte-forms/)

**Comment by dextermb** [comment]
@chainlist I've just ran into this issue, looking through the v2 documentation I don't see anything about manually setting errors.

_I've also noticed some of the sidebar links don't go to the right sections_

**Comment by aniolekx** [comment]
This issue was closed, but it is still not clear how to add errors from server (or API). When I submit form, server side validation can return additinal errors related to particular field, how can I add these errors to field to render it? I have tested today several solutions but nothing was working. These errors from server were not rendered in form. This seems to be common requirement.

**Comment by aniolekx** [comment]
> Hi,
> 
> A v2 of svelte-forms has been released that fixes this use case. Check out the new [documentation website](https://chainlist.github.io/svelte-forms/)

can find anything related :/

**Comment by aniolekx** [comment]
`    async function set(field, forceValidation = false) {
        if (!isField(field)) {
            field = processField(get(store), [], { value: field });
        }
        if (forceValidation || options.validateOnChange) {
            let validations = await getErrors(field, validators, options.stopAtFirstError);
            _set(processField(field, validations, { dirty: true }));
        }
        else {
            _set(processField(field, null, { dirty: true }));
        }
    }`

ok, maybe I have found the problem, even when forceValidation is set to false, options.validateOnChange is triggering validation and overwrites my custom errors, unfortunately I cannot disable it because this will affect user experience, but I need a method to set it without triggering any validation, otherwise it will overwrite my custom errors, any suggestions?
